name: saleem
favicon: null
layout_spectrum: 0.6995977349579334
typography_spectrum: 0.7032838191371411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#ffffff'
    - '#694215'
    - '#be2418'
    - '#d89d40'
  brandStrength: 0.3125
  lightness: 0.4524886088911444
  saturation: 0.3679455714300275
  rhythmicContrast: 0.9958025712985545
purpose: []
